// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Set struct {
	ID        int32
	ShowID    int32
	SetName   string
	Position  int32
	CreatedAt time.Time
}

type SetEntry struct {
	ID       int32
	SetID    int32
	RawEntry string
	Position int32
	CratedAt time.Time
}

type Show struct {
	ShowID    int32
	ShowDate  time.Time
	Day       sql.NullString
	City      string
	State     string
	Venue     string
	Notes     sql.NullString
	CreatedAt time.Time
}
