// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Set struct {
	ID       int32
	ShowID   int32
	SetName  string
	Position int32
}

type SetlistEntry struct {
	ID       int32
	SetID    int32
	RawEntry string
	Position int32
}

type Show struct {
	ShowID   int32
	Date     time.Time
	Day      sql.NullString
	Venue    string
	Location string
	Notes    sql.NullString
}
