// Package database .
// Hand-written file - not generated by sqlc. Safe from sqlc generate.
package database

import (
	"database/sql"
	"time"
)

/*
	sqlc generates different struct types per query, even with identical-looking columns.
	So we use these interfaces + getter methods, plus a mapping function to make it cleaner
	when mapping sqlc structs in the endpoint handlers.
*/

type ShowRow interface {
	GetShowID() int32
	GetShowDate() time.Time
	GetVenue() string
	GetCity() string
	GetLocation() string
	GetNotes() sql.NullString
	GetSetName() sql.NullString
	GetRawEntry() sql.NullString
}

func (r GetShowFromIDRow) GetShowID() int32            { return r.ShowID }
func (r GetShowFromIDRow) GetShowDate() time.Time      { return r.ShowDate }
func (r GetShowFromIDRow) GetVenue() string            { return r.Venue }
func (r GetShowFromIDRow) GetCity() string             { return r.City }
func (r GetShowFromIDRow) GetLocation() string         { return r.Location }
func (r GetShowFromIDRow) GetNotes() sql.NullString    { return r.Notes }
func (r GetShowFromIDRow) GetSetName() sql.NullString  { return r.SetName }
func (r GetShowFromIDRow) GetRawEntry() sql.NullString { return r.RawEntry }

func (r GetShowFromDateRow) GetShowID() int32            { return r.ShowID }
func (r GetShowFromDateRow) GetShowDate() time.Time      { return r.ShowDate }
func (r GetShowFromDateRow) GetVenue() string            { return r.Venue }
func (r GetShowFromDateRow) GetCity() string             { return r.City }
func (r GetShowFromDateRow) GetLocation() string         { return r.Location }
func (r GetShowFromDateRow) GetNotes() sql.NullString    { return r.Notes }
func (r GetShowFromDateRow) GetSetName() sql.NullString  { return r.SetName }
func (r GetShowFromDateRow) GetRawEntry() sql.NullString { return r.RawEntry }

//------------------------------------------------------------------------------------

type SongCountRow interface {
	GetSongName() sql.NullString
	GetTimesPlayed() int64
}

func (r MostCommonSongsBySetNameRow) GetSongName() sql.NullString { return r.Song }
func (r MostCommonSongsBySetNameRow) GetTimesPlayed() int64       { return r.TimesPlayed }

func (r MostPlayedSongsRow) GetSongName() sql.NullString { return r.Song }
func (r MostPlayedSongsRow) GetTimesPlayed() int64       { return r.TimesPlayed }

func (r SongsPlayedLessThanRow) GetSongName() sql.NullString { return r.Song }
func (r SongsPlayedLessThanRow) GetTimesPlayed() int64       { return r.TimesPlayed }

//------------------------------------------------------------------------------------

type ShowSummaryRow interface {
	GetShowID() int32
	GetShowDate() time.Time
	GetVenue() string
	GetCity() string
	GetLocation() string
	GetNotes() sql.NullString
}

func (r ShowsWithShowNotesRow) GetShowID() int32         { return r.ShowID }
func (r ShowsWithShowNotesRow) GetShowDate() time.Time   { return r.ShowDate }
func (r ShowsWithShowNotesRow) GetVenue() string         { return r.Venue }
func (r ShowsWithShowNotesRow) GetCity() string          { return r.City }
func (r ShowsWithShowNotesRow) GetLocation() string      { return r.Location }
func (r ShowsWithShowNotesRow) GetNotes() sql.NullString { return r.Notes }

func (r ShowsWithoutNotesRow) GetShowID() int32         { return r.ShowID }
func (r ShowsWithoutNotesRow) GetShowDate() time.Time   { return r.ShowDate }
func (r ShowsWithoutNotesRow) GetVenue() string         { return r.Venue }
func (r ShowsWithoutNotesRow) GetCity() string          { return r.City }
func (r ShowsWithoutNotesRow) GetLocation() string      { return r.Location }
func (r ShowsWithoutNotesRow) GetNotes() sql.NullString { return sql.NullString{} }

func (r SearchByVenueRow) GetShowID() int32         { return r.ShowID }
func (r SearchByVenueRow) GetShowDate() time.Time   { return r.ShowDate }
func (r SearchByVenueRow) GetVenue() string         { return r.Venue }
func (r SearchByVenueRow) GetCity() string          { return r.City }
func (r SearchByVenueRow) GetLocation() string      { return r.Location }
func (r SearchByVenueRow) GetNotes() sql.NullString { return r.Notes }

func (r GetShowsFromSetNameRow) GetShowID() int32         { return r.ShowID }
func (r GetShowsFromSetNameRow) GetShowDate() time.Time   { return r.ShowDate }
func (r GetShowsFromSetNameRow) GetVenue() string         { return r.Venue }
func (r GetShowsFromSetNameRow) GetCity() string          { return r.City }
func (r GetShowsFromSetNameRow) GetLocation() string      { return r.Location }
func (r GetShowsFromSetNameRow) GetNotes() sql.NullString { return r.Notes }

func (r GetShowsFromSongNameRow) GetShowID() int32         { return r.ShowID }
func (r GetShowsFromSongNameRow) GetShowDate() time.Time   { return r.ShowDate }
func (r GetShowsFromSongNameRow) GetVenue() string         { return r.Venue }
func (r GetShowsFromSongNameRow) GetCity() string          { return r.City }
func (r GetShowsFromSongNameRow) GetLocation() string      { return r.Location }
func (r GetShowsFromSongNameRow) GetNotes() sql.NullString { return r.Notes }

func (r GetShowsBetweenDatesRow) GetShowID() int32         { return r.ShowID }
func (r GetShowsBetweenDatesRow) GetShowDate() time.Time   { return r.ShowDate }
func (r GetShowsBetweenDatesRow) GetVenue() string         { return r.Venue }
func (r GetShowsBetweenDatesRow) GetCity() string          { return r.City }
func (r GetShowsBetweenDatesRow) GetLocation() string      { return r.Location }
func (r GetShowsBetweenDatesRow) GetNotes() sql.NullString { return r.Notes }

func (r GetShowsFromYearAndLocationRow) GetShowID() int32         { return r.ShowID }
func (r GetShowsFromYearAndLocationRow) GetShowDate() time.Time   { return r.ShowDate }
func (r GetShowsFromYearAndLocationRow) GetVenue() string         { return r.Venue }
func (r GetShowsFromYearAndLocationRow) GetCity() string          { return r.City }
func (r GetShowsFromYearAndLocationRow) GetLocation() string      { return r.Location }
func (r GetShowsFromYearAndLocationRow) GetNotes() sql.NullString { return r.Notes }

func (r GetShowsFromYearRow) GetShowID() int32         { return r.ShowID }
func (r GetShowsFromYearRow) GetShowDate() time.Time   { return r.ShowDate }
func (r GetShowsFromYearRow) GetVenue() string         { return r.Venue }
func (r GetShowsFromYearRow) GetCity() string          { return r.City }
func (r GetShowsFromYearRow) GetLocation() string      { return r.Location }
func (r GetShowsFromYearRow) GetNotes() sql.NullString { return r.Notes }

func (r GetShowsFromLocationRow) GetShowID() int32         { return r.ShowID }
func (r GetShowsFromLocationRow) GetShowDate() time.Time   { return r.ShowDate }
func (r GetShowsFromLocationRow) GetVenue() string         { return r.Venue }
func (r GetShowsFromLocationRow) GetCity() string          { return r.City }
func (r GetShowsFromLocationRow) GetLocation() string      { return r.Location }
func (r GetShowsFromLocationRow) GetNotes() sql.NullString { return r.Notes }

func (r GetShowsFromCityRow) GetShowID() int32         { return r.ShowID }
func (r GetShowsFromCityRow) GetShowDate() time.Time   { return r.ShowDate }
func (r GetShowsFromCityRow) GetVenue() string         { return r.Venue }
func (r GetShowsFromCityRow) GetCity() string          { return r.City }
func (r GetShowsFromCityRow) GetLocation() string      { return r.Location }
func (r GetShowsFromCityRow) GetNotes() sql.NullString { return r.Notes }
