// Package database .
// Hand-written file - not generated by sqlc. Safe from sqlc generate.
package database

import (
	"database/sql"
	"time"

	"github.com/LunarDrift/deadabase/internal"
)

type ShowRow interface {
	GetShowID() int32
	GetShowDate() time.Time
	GetVenue() string
	GetCity() string
	GetState() string
	GetNotes() sql.NullString
	GetSetName() sql.NullString
	GetRawEntry() sql.NullString
}

func (r GetShowFromIDRow) GetShowID() int32            { return r.ShowID }
func (r GetShowFromIDRow) GetShowDate() time.Time      { return r.ShowDate }
func (r GetShowFromIDRow) GetVenue() string            { return r.Venue }
func (r GetShowFromIDRow) GetCity() string             { return r.City }
func (r GetShowFromIDRow) GetState() string            { return r.State }
func (r GetShowFromIDRow) GetNotes() sql.NullString    { return r.Notes }
func (r GetShowFromIDRow) GetSetName() sql.NullString  { return r.SetName }
func (r GetShowFromIDRow) GetRawEntry() sql.NullString { return r.RawEntry }

func (r GetShowFromDateRow) GetShowID() int32            { return r.ShowID }
func (r GetShowFromDateRow) GetShowDate() time.Time      { return r.ShowDate }
func (r GetShowFromDateRow) GetVenue() string            { return r.Venue }
func (r GetShowFromDateRow) GetCity() string             { return r.City }
func (r GetShowFromDateRow) GetState() string            { return r.State }
func (r GetShowFromDateRow) GetNotes() sql.NullString    { return r.Notes }
func (r GetShowFromDateRow) GetSetName() sql.NullString  { return r.SetName }
func (r GetShowFromDateRow) GetRawEntry() sql.NullString { return r.RawEntry }

func RowToShowSortInput(r ShowRow) internal.ShowSortInput {
	return internal.ShowSortInput{
		ShowID:   r.GetShowID(),
		ShowDate: r.GetShowDate(),
		Venue:    r.GetVenue(),
		City:     r.GetCity(),
		State:    r.GetState(),
		Notes:    r.GetNotes().String,
		SetName:  r.GetSetName().String,
		RawEntry: r.GetRawEntry().String,
	}
}

type SongCountRow interface {
	GetSongName() sql.NullString
	GetTimesPlayed() int64
}

func (r MostCommonEncoreRow) GetSongName() sql.NullString { return r.Song }
func (r MostCommonEncoreRow) GetTimesPlayed() int64       { return r.TimesPlayed }

func (r MostPlayedSongsRow) GetSongName() sql.NullString { return r.Song }
func (r MostPlayedSongsRow) GetTimesPlayed() int64       { return r.TimesPlayed }

func (r SongsPlayedLessThanRow) GetSongName() sql.NullString { return r.Song }
func (r SongsPlayedLessThanRow) GetTimesPlayed() int64       { return r.TimesPlayed }

func RowToSongsTimesPlayed(r SongCountRow) internal.SongsTimesPlayed {
	return internal.SongsTimesPlayed{
		Song:        r.GetSongName().String,
		TimesPlayed: int(r.GetTimesPlayed()),
	}
}
