// Package database .
// Hand-written file - not generated by sqlc. Safe from sqlc generate.
package database

import (
	"database/sql"
	"time"

	"github.com/LunarDrift/deadabase/internal"
)

/*
	sqlc generates different struct types per query, even with identical-looking columns.
	So we use these interfaces + getter methods, plus a mapping function to make it cleaner
	when mapping sqlc structs in the endpoint handlers.
*/

type ShowRow interface {
	GetShowID() int32
	GetShowDate() time.Time
	GetVenue() string
	GetCity() string
	GetState() string
	GetNotes() sql.NullString
	GetSetName() sql.NullString
	GetRawEntry() sql.NullString
}

func (r GetShowFromIDRow) GetShowID() int32            { return r.ShowID }
func (r GetShowFromIDRow) GetShowDate() time.Time      { return r.ShowDate }
func (r GetShowFromIDRow) GetVenue() string            { return r.Venue }
func (r GetShowFromIDRow) GetCity() string             { return r.City }
func (r GetShowFromIDRow) GetState() string            { return r.State }
func (r GetShowFromIDRow) GetNotes() sql.NullString    { return r.Notes }
func (r GetShowFromIDRow) GetSetName() sql.NullString  { return r.SetName }
func (r GetShowFromIDRow) GetRawEntry() sql.NullString { return r.RawEntry }

func (r GetShowFromDateRow) GetShowID() int32            { return r.ShowID }
func (r GetShowFromDateRow) GetShowDate() time.Time      { return r.ShowDate }
func (r GetShowFromDateRow) GetVenue() string            { return r.Venue }
func (r GetShowFromDateRow) GetCity() string             { return r.City }
func (r GetShowFromDateRow) GetState() string            { return r.State }
func (r GetShowFromDateRow) GetNotes() sql.NullString    { return r.Notes }
func (r GetShowFromDateRow) GetSetName() sql.NullString  { return r.SetName }
func (r GetShowFromDateRow) GetRawEntry() sql.NullString { return r.RawEntry }

func RowToShowSortInput(r ShowRow) internal.ShowSortInput {
	return internal.ShowSortInput{
		ShowID:   r.GetShowID(),
		ShowDate: r.GetShowDate(),
		Venue:    r.GetVenue(),
		City:     r.GetCity(),
		State:    r.GetState(),
		Notes:    r.GetNotes().String,
		SetName:  r.GetSetName().String,
		RawEntry: r.GetRawEntry().String,
	}
}

type SongCountRow interface {
	GetSongName() sql.NullString
	GetTimesPlayed() int64
}

func (r MostCommonEncoreRow) GetSongName() sql.NullString { return r.Song }
func (r MostCommonEncoreRow) GetTimesPlayed() int64       { return r.TimesPlayed }

func (r MostPlayedSongsRow) GetSongName() sql.NullString { return r.Song }
func (r MostPlayedSongsRow) GetTimesPlayed() int64       { return r.TimesPlayed }

func (r SongsPlayedLessThanRow) GetSongName() sql.NullString { return r.Song }
func (r SongsPlayedLessThanRow) GetTimesPlayed() int64       { return r.TimesPlayed }

func RowToSongsTimesPlayed(r SongCountRow) internal.SongsTimesPlayed {
	return internal.SongsTimesPlayed{
		Song:        r.GetSongName().String,
		TimesPlayed: int(r.GetTimesPlayed()),
	}
}

type ShowSummaryRow interface {
	GetShowID() int32
	GetShowDate() time.Time
	GetVenue() string
	GetCity() string
	GetState() string
	GetNotes() sql.NullString
}

func (r ShowsWithShowNotesRow) GetShowID() int32         { return r.ShowID }
func (r ShowsWithShowNotesRow) GetShowDate() time.Time   { return r.ShowDate }
func (r ShowsWithShowNotesRow) GetVenue() string         { return r.Venue }
func (r ShowsWithShowNotesRow) GetCity() string          { return r.City }
func (r ShowsWithShowNotesRow) GetState() string         { return r.State }
func (r ShowsWithShowNotesRow) GetNotes() sql.NullString { return r.Notes }

func (r ShowsWithoutNotesRow) GetShowID() int32         { return r.ShowID }
func (r ShowsWithoutNotesRow) GetShowDate() time.Time   { return r.ShowDate }
func (r ShowsWithoutNotesRow) GetVenue() string         { return r.Venue }
func (r ShowsWithoutNotesRow) GetCity() string          { return r.City }
func (r ShowsWithoutNotesRow) GetState() string         { return r.State }
func (r ShowsWithoutNotesRow) GetNotes() sql.NullString { return sql.NullString{} }

func (r SearchByVenueRow) GetShowID() int32         { return r.ShowID }
func (r SearchByVenueRow) GetShowDate() time.Time   { return r.ShowDate }
func (r SearchByVenueRow) GetVenue() string         { return r.Venue }
func (r SearchByVenueRow) GetCity() string          { return r.City }
func (r SearchByVenueRow) GetState() string         { return r.State }
func (r SearchByVenueRow) GetNotes() sql.NullString { return r.Notes }

func (r GetShowsFromSetNameRow) GetShowID() int32         { return r.ShowID }
func (r GetShowsFromSetNameRow) GetShowDate() time.Time   { return r.ShowDate }
func (r GetShowsFromSetNameRow) GetVenue() string         { return r.Venue }
func (r GetShowsFromSetNameRow) GetCity() string          { return r.City }
func (r GetShowsFromSetNameRow) GetState() string         { return r.State }
func (r GetShowsFromSetNameRow) GetNotes() sql.NullString { return sql.NullString{} }

func RowToShowMeta(r ShowSummaryRow) internal.ShowMeta {
	return internal.ShowMeta{
		ShowID: r.GetShowID(),
		Date:   r.GetShowDate().Format(time.DateOnly),
		Venue:  r.GetVenue(),
		City:   r.GetCity(),
		State:  r.GetState(),
		Notes:  r.GetNotes().String,
	}
}
