// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: set_entries.sql

package database

import (
	"context"
)

const createSetEntry = `-- name: CreateSetEntry :exec
INSERT INTO set_entries (
set_id,
raw_entry,
position
)
VALUES (
  $1,
  $2,
  $3
  )
ON CONFLICT (set_id, position) DO NOTHING
`

type CreateSetEntryParams struct {
	SetID    int32
	RawEntry string
	Position int32
}

func (q *Queries) CreateSetEntry(ctx context.Context, arg CreateSetEntryParams) error {
	_, err := q.db.ExecContext(ctx, createSetEntry, arg.SetID, arg.RawEntry, arg.Position)
	return err
}

const mostPlayedSongs = `-- name: MostPlayedSongs :many
SELECT se.raw_entry AS song, count(*) AS times_played
FROM set_entries se
GROUP BY se.raw_entry
ORDER BY times_played DESC
`

type MostPlayedSongsRow struct {
	Song        string
	TimesPlayed int64
}

func (q *Queries) MostPlayedSongs(ctx context.Context) ([]MostPlayedSongsRow, error) {
	rows, err := q.db.QueryContext(ctx, mostPlayedSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MostPlayedSongsRow
	for rows.Next() {
		var i MostPlayedSongsRow
		if err := rows.Scan(&i.Song, &i.TimesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
