// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: set_entries.sql

package database

import (
	"context"
	"database/sql"
)

const allSongsPlayedAtVenue = `-- name: AllSongsPlayedAtVenue :many
SELECT DISTINCT se.song_name, sh.venue, sh.city, sh.state
FROM set_entries se
JOIN "sets" s ON se.set_id = s.id
JOIN shows sh ON s.show_id = sh.show_id
WHERE sh.venue ILIKE $1
ORDER BY sh.venue, se.song_name
`

type AllSongsPlayedAtVenueRow struct {
	SongName sql.NullString
	Venue    string
	City     string
	State    string
}

func (q *Queries) AllSongsPlayedAtVenue(ctx context.Context, venue string) ([]AllSongsPlayedAtVenueRow, error) {
	rows, err := q.db.QueryContext(ctx, allSongsPlayedAtVenue, venue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllSongsPlayedAtVenueRow
	for rows.Next() {
		var i AllSongsPlayedAtVenueRow
		if err := rows.Scan(
			&i.SongName,
			&i.Venue,
			&i.City,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSetEntry = `-- name: CreateSetEntry :exec
INSERT INTO set_entries (
set_id,
raw_entry,
position
)
VALUES (
  $1,
  $2,
  $3
  )
ON CONFLICT (set_id, position) DO NOTHING
`

type CreateSetEntryParams struct {
	SetID    int32
	RawEntry string
	Position int32
}

func (q *Queries) CreateSetEntry(ctx context.Context, arg CreateSetEntryParams) error {
	_, err := q.db.ExecContext(ctx, createSetEntry, arg.SetID, arg.RawEntry, arg.Position)
	return err
}

const mostCommonSongsBySetName = `-- name: MostCommonSongsBySetName :many
SELECT se.song_name AS song, count(*) AS times_played
FROM set_entries se 
JOIN "sets" s ON se.set_id = s.id
WHERE s.set_name = $1
GROUP BY se.song_name 
ORDER BY times_played  DESC
`

type MostCommonSongsBySetNameRow struct {
	Song        sql.NullString
	TimesPlayed int64
}

func (q *Queries) MostCommonSongsBySetName(ctx context.Context, setName string) ([]MostCommonSongsBySetNameRow, error) {
	rows, err := q.db.QueryContext(ctx, mostCommonSongsBySetName, setName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MostCommonSongsBySetNameRow
	for rows.Next() {
		var i MostCommonSongsBySetNameRow
		if err := rows.Scan(&i.Song, &i.TimesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mostPlayedSongs = `-- name: MostPlayedSongs :many
SELECT se.song_name AS song, count(*) AS times_played
FROM set_entries se
GROUP BY se.song_name
ORDER BY times_played DESC
`

type MostPlayedSongsRow struct {
	Song        sql.NullString
	TimesPlayed int64
}

func (q *Queries) MostPlayedSongs(ctx context.Context) ([]MostPlayedSongsRow, error) {
	rows, err := q.db.QueryContext(ctx, mostPlayedSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MostPlayedSongsRow
	for rows.Next() {
		var i MostPlayedSongsRow
		if err := rows.Scan(&i.Song, &i.TimesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const songsPlayedLessThan = `-- name: SongsPlayedLessThan :many
SELECT se.song_name AS song, count(*) AS times_played
FROM set_entries se
GROUP BY se.song_name
HAVING count(*) < $1::int
ORDER BY times_played DESC
`

type SongsPlayedLessThanRow struct {
	Song        sql.NullString
	TimesPlayed int64
}

func (q *Queries) SongsPlayedLessThan(ctx context.Context, dollar_1 int32) ([]SongsPlayedLessThanRow, error) {
	rows, err := q.db.QueryContext(ctx, songsPlayedLessThan, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SongsPlayedLessThanRow
	for rows.Next() {
		var i SongsPlayedLessThanRow
		if err := rows.Scan(&i.Song, &i.TimesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uniqueSongsPerCity = `-- name: UniqueSongsPerCity :many
SELECT sh.city, sh.state AS state_or_country, count(DISTINCT se.song_name) AS unique_song_count
FROM set_entries se
JOIN "sets" s ON se.set_id = s.id
JOIN shows sh ON s.show_id = sh.show_id
GROUP BY sh.city, sh.state
ORDER BY unique_song_count DESC
`

type UniqueSongsPerCityRow struct {
	City            string
	StateOrCountry  string
	UniqueSongCount int64
}

func (q *Queries) UniqueSongsPerCity(ctx context.Context) ([]UniqueSongsPerCityRow, error) {
	rows, err := q.db.QueryContext(ctx, uniqueSongsPerCity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UniqueSongsPerCityRow
	for rows.Next() {
		var i UniqueSongsPerCityRow
		if err := rows.Scan(&i.City, &i.StateOrCountry, &i.UniqueSongCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
