// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: set_entries.sql

package database

import (
	"context"
	"database/sql"
)

const createSetEntry = `-- name: CreateSetEntry :exec
INSERT INTO set_entries (
set_id,
raw_entry,
position
)
VALUES (
  $1,
  $2,
  $3
  )
ON CONFLICT (set_id, position) DO NOTHING
`

type CreateSetEntryParams struct {
	SetID    int32
	RawEntry string
	Position int32
}

func (q *Queries) CreateSetEntry(ctx context.Context, arg CreateSetEntryParams) error {
	_, err := q.db.ExecContext(ctx, createSetEntry, arg.SetID, arg.RawEntry, arg.Position)
	return err
}

const mostCommonEncore = `-- name: MostCommonEncore :many
SELECT se.song_name AS song, count(*) AS times_played
FROM set_entries se 
JOIN "sets" s ON se.set_id = s.id
WHERE s.set_name = 'encore'
GROUP BY se.song_name 
ORDER BY times_played  DESC
`

type MostCommonEncoreRow struct {
	Song        sql.NullString
	TimesPlayed int64
}

func (q *Queries) MostCommonEncore(ctx context.Context) ([]MostCommonEncoreRow, error) {
	rows, err := q.db.QueryContext(ctx, mostCommonEncore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MostCommonEncoreRow
	for rows.Next() {
		var i MostCommonEncoreRow
		if err := rows.Scan(&i.Song, &i.TimesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mostPlayedSongs = `-- name: MostPlayedSongs :many
SELECT se.song_name AS song, count(*) AS times_played
FROM set_entries se
GROUP BY se.song_name
ORDER BY times_played DESC
`

type MostPlayedSongsRow struct {
	Song        sql.NullString
	TimesPlayed int64
}

func (q *Queries) MostPlayedSongs(ctx context.Context) ([]MostPlayedSongsRow, error) {
	rows, err := q.db.QueryContext(ctx, mostPlayedSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MostPlayedSongsRow
	for rows.Next() {
		var i MostPlayedSongsRow
		if err := rows.Scan(&i.Song, &i.TimesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const songsPlayedLessThan = `-- name: SongsPlayedLessThan :many
SELECT se.song_name AS song, count(*) AS times_played
FROM set_entries se
GROUP BY se.song_name
HAVING count(*) < $1
ORDER BY times_played DESC
`

type SongsPlayedLessThanRow struct {
	Song        sql.NullString
	TimesPlayed int64
}

func (q *Queries) SongsPlayedLessThan(ctx context.Context, dollar_1 interface{}) ([]SongsPlayedLessThanRow, error) {
	rows, err := q.db.QueryContext(ctx, songsPlayedLessThan, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SongsPlayedLessThanRow
	for rows.Next() {
		var i SongsPlayedLessThanRow
		if err := rows.Scan(&i.Song, &i.TimesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
