// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setlist_entries.sql

package database

import (
	"context"
)

const insertSetlistEntry = `-- name: InsertSetlistEntry :exec
INSERT INTO setlist_entries (set_id, raw_entry, position)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertSetlistEntryParams struct {
	SetID    int32
	RawEntry string
	Position int32
}

func (q *Queries) InsertSetlistEntry(ctx context.Context, arg InsertSetlistEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertSetlistEntry, arg.SetID, arg.RawEntry, arg.Position)
	return err
}
