// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sets.sql

package database

import (
	"context"
)

const createSet = `-- name: CreateSet :one
INSERT INTO sets (
show_id,
set_name,
position
)
VALUES (
  $1,
  $2,
  $3
)
RETURNING id
`

type CreateSetParams struct {
	ShowID   int32
	SetName  string
	Position int32
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createSet, arg.ShowID, arg.SetName, arg.Position)
	var id int32
	err := row.Scan(&id)
	return id, err
}
