// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sets.sql

package database

import (
	"context"
)

const insertSet = `-- name: InsertSet :one
INSERT INTO sets (show_id, set_name, position)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertSetParams struct {
	ShowID   int32
	SetName  string
	Position int32
}

func (q *Queries) InsertSet(ctx context.Context, arg InsertSetParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertSet, arg.ShowID, arg.SetName, arg.Position)
	var id int32
	err := row.Scan(&id)
	return id, err
}
