// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: show_footnotes.sql

package database

import (
	"context"
)

const createFootnote = `-- name: CreateFootnote :exec
INSERT INTO show_footnotes (show_id, marker, note_text)
VALUES ($1, $2, $3)
ON CONFLICT (show_id, marker) DO NOTHING
RETURNING id, show_id, marker, note_text
`

type CreateFootnoteParams struct {
	ShowID   int32
	Marker   string
	NoteText string
}

func (q *Queries) CreateFootnote(ctx context.Context, arg CreateFootnoteParams) error {
	_, err := q.db.ExecContext(ctx, createFootnote, arg.ShowID, arg.Marker, arg.NoteText)
	return err
}

const getFootnotesFromShowID = `-- name: GetFootnotesFromShowID :many
SELECT marker, note_text
FROM show_footnotes
WHERE show_id = $1
`

type GetFootnotesFromShowIDRow struct {
	Marker   string
	NoteText string
}

func (q *Queries) GetFootnotesFromShowID(ctx context.Context, showID int32) ([]GetFootnotesFromShowIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getFootnotesFromShowID, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFootnotesFromShowIDRow
	for rows.Next() {
		var i GetFootnotesFromShowIDRow
		if err := rows.Scan(&i.Marker, &i.NoteText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
