// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shows.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createShow = `-- name: CreateShow :exec
INSERT INTO shows (
show_id,
show_date,
day,
city,
state,
venue,
notes
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
ON CONFLICT (show_id) DO NOTHING
`

type CreateShowParams struct {
	ShowID   int32
	ShowDate time.Time
	Day      sql.NullString
	City     string
	State    string
	Venue    string
	Notes    sql.NullString
}

func (q *Queries) CreateShow(ctx context.Context, arg CreateShowParams) error {
	_, err := q.db.ExecContext(ctx, createShow,
		arg.ShowID,
		arg.ShowDate,
		arg.Day,
		arg.City,
		arg.State,
		arg.Venue,
		arg.Notes,
	)
	return err
}

const getAllShowIDs = `-- name: GetAllShowIDs :many
SELECT show_id FROM shows ORDER BY show_id
`

func (q *Queries) GetAllShowIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAllShowIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var show_id int32
		if err := rows.Scan(&show_id); err != nil {
			return nil, err
		}
		items = append(items, show_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowFromDate = `-- name: GetShowFromDate :many
SELECT 
	shows.show_date,
	shows.venue,
  shows.city,
  shows.state,
  shows.notes,
	sets.set_name,
	sets.position AS set_position,
	set_entries.raw_entry,
	set_entries.position AS song_position
FROM
	shows
LEFT JOIN SETS ON
	sets.show_id = shows.show_id
LEFT JOIN set_entries ON
	set_entries.set_id = sets.id
WHERE
	shows.show_date = $1
ORDER BY
  shows.show_id,
	sets.position,
	set_entries."position"
`

type GetShowFromDateRow struct {
	ShowDate     time.Time
	Venue        string
	City         string
	State        string
	Notes        sql.NullString
	SetName      sql.NullString
	SetPosition  sql.NullInt32
	RawEntry     sql.NullString
	SongPosition sql.NullInt32
}

func (q *Queries) GetShowFromDate(ctx context.Context, showDate time.Time) ([]GetShowFromDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowFromDate, showDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowFromDateRow
	for rows.Next() {
		var i GetShowFromDateRow
		if err := rows.Scan(
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
			&i.Notes,
			&i.SetName,
			&i.SetPosition,
			&i.RawEntry,
			&i.SongPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowFromID = `-- name: GetShowFromID :many
SELECT
	s.show_date,
	s.venue,
  s.city,
  s.state,
  s.notes,
	st.set_name,
	se.raw_entry
FROM
	shows s
LEFT JOIN SETS st
	ON
	s.show_id = st.show_id
LEFT JOIN set_entries se
	ON
	st.id = se.set_id
WHERE
	s.show_id = $1
ORDER BY
	st.position,
	se.position
`

type GetShowFromIDRow struct {
	ShowDate time.Time
	Venue    string
	City     string
	State    string
	Notes    sql.NullString
	SetName  sql.NullString
	RawEntry sql.NullString
}

func (q *Queries) GetShowFromID(ctx context.Context, showID int32) ([]GetShowFromIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowFromID, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowFromIDRow
	for rows.Next() {
		var i GetShowFromIDRow
		if err := rows.Scan(
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
			&i.Notes,
			&i.SetName,
			&i.RawEntry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVenue = `-- name: SearchByVenue :many
SELECT
  shows.show_id,
	shows.show_date AS "date",
	shows.venue,
  shows.city,
  shows.state
FROM
	shows
WHERE venue ILIKE $1
ORDER BY
  shows.show_id,
	shows.venue,
	shows.show_date
`

type SearchByVenueRow struct {
	ShowID int32
	Date   time.Time
	Venue  string
	City   string
	State  string
}

func (q *Queries) SearchByVenue(ctx context.Context, venue string) ([]SearchByVenueRow, error) {
	rows, err := q.db.QueryContext(ctx, searchByVenue, venue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchByVenueRow
	for rows.Next() {
		var i SearchByVenueRow
		if err := rows.Scan(
			&i.ShowID,
			&i.Date,
			&i.Venue,
			&i.City,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
