// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shows.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createShow = `-- name: CreateShow :exec
INSERT INTO shows (
show_id,
show_date,
day,
city,
state,
venue,
notes
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
ON CONFLICT (show_id) DO NOTHING
`

type CreateShowParams struct {
	ShowID   int32
	ShowDate time.Time
	Day      sql.NullString
	City     string
	State    string
	Venue    string
	Notes    sql.NullString
}

func (q *Queries) CreateShow(ctx context.Context, arg CreateShowParams) error {
	_, err := q.db.ExecContext(ctx, createShow,
		arg.ShowID,
		arg.ShowDate,
		arg.Day,
		arg.City,
		arg.State,
		arg.Venue,
		arg.Notes,
	)
	return err
}

const getAllShowIDs = `-- name: GetAllShowIDs :many
SELECT show_id FROM shows ORDER BY show_id
`

func (q *Queries) GetAllShowIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAllShowIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var show_id int32
		if err := rows.Scan(&show_id); err != nil {
			return nil, err
		}
		items = append(items, show_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowFromDate = `-- name: GetShowFromDate :many
SELECT 
  shows.show_id,
	shows.show_date,
	shows.venue,
  shows.city,
  shows.state,
  shows.notes,
	sets.set_name,
	sets.position AS set_position,
	set_entries.raw_entry,
	set_entries.position AS song_position
FROM
	shows
LEFT JOIN SETS ON
	sets.show_id = shows.show_id
LEFT JOIN set_entries ON
	set_entries.set_id = sets.id
WHERE
	shows.show_date = $1
ORDER BY
  shows.show_id,
	sets.position,
	set_entries."position"
`

type GetShowFromDateRow struct {
	ShowID       int32
	ShowDate     time.Time
	Venue        string
	City         string
	State        string
	Notes        sql.NullString
	SetName      sql.NullString
	SetPosition  sql.NullInt32
	RawEntry     sql.NullString
	SongPosition sql.NullInt32
}

func (q *Queries) GetShowFromDate(ctx context.Context, showDate time.Time) ([]GetShowFromDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowFromDate, showDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowFromDateRow
	for rows.Next() {
		var i GetShowFromDateRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
			&i.Notes,
			&i.SetName,
			&i.SetPosition,
			&i.RawEntry,
			&i.SongPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowFromID = `-- name: GetShowFromID :many
SELECT
  s.show_id,
	s.show_date,
	s.venue,
  s.city,
  s.state,
  s.notes,
	st.set_name,
	se.raw_entry
FROM
	shows s
LEFT JOIN SETS st
	ON
	s.show_id = st.show_id
LEFT JOIN set_entries se
	ON
	st.id = se.set_id
WHERE
	s.show_id = $1
ORDER BY
	st.position,
	se.position
`

type GetShowFromIDRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	State    string
	Notes    sql.NullString
	SetName  sql.NullString
	RawEntry sql.NullString
}

func (q *Queries) GetShowFromID(ctx context.Context, showID int32) ([]GetShowFromIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowFromID, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowFromIDRow
	for rows.Next() {
		var i GetShowFromIDRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
			&i.Notes,
			&i.SetName,
			&i.RawEntry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsBetweenDates = `-- name: GetShowsBetweenDates :many
SELECT
  s.show_id,
	s.show_date,
	s.venue,
	s.city,
	s.state,
  s.notes
FROM
	shows s
JOIN "sets" st ON 
	s.show_id = st.show_id 
JOIN set_entries se ON
	st.id = se.set_id 
WHERE
	s.show_date BETWEEN $1 AND $2
GROUP BY
	s.show_date, s.venue, s.show_id 
ORDER BY
	s.show_date
`

type GetShowsBetweenDatesParams struct {
	ShowDate   time.Time
	ShowDate_2 time.Time
}

type GetShowsBetweenDatesRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	State    string
	Notes    sql.NullString
}

func (q *Queries) GetShowsBetweenDates(ctx context.Context, arg GetShowsBetweenDatesParams) ([]GetShowsBetweenDatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsBetweenDates, arg.ShowDate, arg.ShowDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsBetweenDatesRow
	for rows.Next() {
		var i GetShowsBetweenDatesRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsFromSetName = `-- name: GetShowsFromSetName :many
SELECT
	sh.show_id,
	sh.show_date,
	sh.venue,
	sh.city,
	sh.state,
  sh.notes
FROM shows sh
JOIN "sets" s ON s.show_id = sh.show_id 
WHERE s.set_name = $1
`

type GetShowsFromSetNameRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	State    string
	Notes    sql.NullString
}

func (q *Queries) GetShowsFromSetName(ctx context.Context, setName string) ([]GetShowsFromSetNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsFromSetName, setName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsFromSetNameRow
	for rows.Next() {
		var i GetShowsFromSetNameRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsFromSongName = `-- name: GetShowsFromSongName :many
SELECT
  s.show_id,
  s.show_date,
  s.venue,
  s.city,
  s.state,
  s.notes
FROM shows s
JOIN "sets" st ON st.show_id = s.show_id
JOIN set_entries se ON se.set_id = st.id
WHERE se.raw_entry ILIKE $1
ORDER BY show_date
`

type GetShowsFromSongNameRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	State    string
	Notes    sql.NullString
}

func (q *Queries) GetShowsFromSongName(ctx context.Context, rawEntry string) ([]GetShowsFromSongNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsFromSongName, rawEntry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsFromSongNameRow
	for rows.Next() {
		var i GetShowsFromSongNameRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsFromYear = `-- name: GetShowsFromYear :many
SELECT
  sh.show_id,
  sh.show_date,
  sh.venue,
  sh.city,
  sh.state,
  sh.notes
FROM shows sh
WHERE EXTRACT(YEAR FROM sh.show_date) = $1::int
ORDER BY sh.show_date
`

type GetShowsFromYearRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	State    string
	Notes    sql.NullString
}

func (q *Queries) GetShowsFromYear(ctx context.Context, year int32) ([]GetShowsFromYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsFromYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsFromYearRow
	for rows.Next() {
		var i GetShowsFromYearRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsFromYearAndState = `-- name: GetShowsFromYearAndState :many
SELECT
  sh.show_id,
  sh.show_date,
  sh.venue,
  sh.city,
  sh.state,
  sh.notes
FROM shows sh
WHERE EXTRACT(YEAR FROM sh.show_date) = $1::int
AND sh.state = $2
ORDER BY sh.show_date
`

type GetShowsFromYearAndStateParams struct {
	Year           int32
	StateOrCountry string
}

type GetShowsFromYearAndStateRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	State    string
	Notes    sql.NullString
}

func (q *Queries) GetShowsFromYearAndState(ctx context.Context, arg GetShowsFromYearAndStateParams) ([]GetShowsFromYearAndStateRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsFromYearAndState, arg.Year, arg.StateOrCountry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsFromYearAndStateRow
	for rows.Next() {
		var i GetShowsFromYearAndStateRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVenue = `-- name: SearchByVenue :many
SELECT
  shows.show_id,
	shows.show_date,
	shows.venue,
  shows.city,
  shows.state,
  shows.notes
FROM
	shows
WHERE venue ILIKE $1
ORDER BY
  shows.show_id,
	shows.venue,
	shows.show_date
`

type SearchByVenueRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	State    string
	Notes    sql.NullString
}

func (q *Queries) SearchByVenue(ctx context.Context, venue string) ([]SearchByVenueRow, error) {
	rows, err := q.db.QueryContext(ctx, searchByVenue, venue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchByVenueRow
	for rows.Next() {
		var i SearchByVenueRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showsWithShowNotes = `-- name: ShowsWithShowNotes :many
SELECT 
	sh.show_id,
	sh.show_date,
	sh.venue,
	sh.city,
	sh.state,
	sh.notes
FROM shows sh
WHERE sh.notes IS NOT NULL AND sh.notes != ''
`

type ShowsWithShowNotesRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	State    string
	Notes    sql.NullString
}

func (q *Queries) ShowsWithShowNotes(ctx context.Context) ([]ShowsWithShowNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, showsWithShowNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowsWithShowNotesRow
	for rows.Next() {
		var i ShowsWithShowNotesRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showsWithoutNotes = `-- name: ShowsWithoutNotes :many
SELECT
  sh.show_id,
  sh.show_date,
  sh.venue,
  sh.city,
  sh.state
FROM shows sh
WHERE sh.notes IS NULL OR sh.notes = ''
`

type ShowsWithoutNotesRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	State    string
}

func (q *Queries) ShowsWithoutNotes(ctx context.Context) ([]ShowsWithoutNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, showsWithoutNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowsWithoutNotesRow
	for rows.Next() {
		var i ShowsWithoutNotesRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const songStats = `-- name: SongStats :one
SELECT
  count(*) AS times_played,
  min(sh.show_date)::date AS first_played,
  max(sh.show_date)::date AS last_played
FROM shows sh 
JOIN "sets" s ON s.show_id = sh.show_id 
JOIN set_entries se ON se.set_id = s.id 
WHERE se.song_name ILIKE $1
`

type SongStatsRow struct {
	TimesPlayed int64
	FirstPlayed time.Time
	LastPlayed  time.Time
}

func (q *Queries) SongStats(ctx context.Context, songName sql.NullString) (SongStatsRow, error) {
	row := q.db.QueryRowContext(ctx, songStats, songName)
	var i SongStatsRow
	err := row.Scan(&i.TimesPlayed, &i.FirstPlayed, &i.LastPlayed)
	return i, err
}
