// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shows.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createShow = `-- name: CreateShow :exec
INSERT INTO shows (
show_id,
show_date,
day,
city,
state,
venue,
notes
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
ON CONFLICT (show_id) DO NOTHING
`

type CreateShowParams struct {
	ShowID   int32
	ShowDate time.Time
	Day      sql.NullString
	City     string
	State    string
	Venue    string
	Notes    sql.NullString
}

func (q *Queries) CreateShow(ctx context.Context, arg CreateShowParams) error {
	_, err := q.db.ExecContext(ctx, createShow,
		arg.ShowID,
		arg.ShowDate,
		arg.Day,
		arg.City,
		arg.State,
		arg.Venue,
		arg.Notes,
	)
	return err
}

const getAllShowIDs = `-- name: GetAllShowIDs :many
SELECT show_id FROM shows ORDER BY show_id
`

func (q *Queries) GetAllShowIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAllShowIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var show_id int32
		if err := rows.Scan(&show_id); err != nil {
			return nil, err
		}
		items = append(items, show_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowFromDate = `-- name: GetShowFromDate :many
SELECT 
  sh.show_id,
	sh.show_date,
	sh.venue,
  sh.city,
  sh.state AS location,
  sh.notes,
	st.set_name,
	st.position AS set_position,
	se.raw_entry,
	se.position AS song_position
FROM
	shows sh
LEFT JOIN "sets" st ON
	st.show_id = sh.show_id
LEFT JOIN set_entries se ON
	se.set_id = st.id
WHERE
	sh.show_date = $1
ORDER BY
  sh.show_id,
	st."position",
	se."position"
`

type GetShowFromDateRow struct {
	ShowID       int32
	ShowDate     time.Time
	Venue        string
	City         string
	Location     string
	Notes        sql.NullString
	SetName      sql.NullString
	SetPosition  sql.NullInt32
	RawEntry     sql.NullString
	SongPosition sql.NullInt32
}

func (q *Queries) GetShowFromDate(ctx context.Context, showDate time.Time) ([]GetShowFromDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowFromDate, showDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowFromDateRow
	for rows.Next() {
		var i GetShowFromDateRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Notes,
			&i.SetName,
			&i.SetPosition,
			&i.RawEntry,
			&i.SongPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowFromID = `-- name: GetShowFromID :many
SELECT
  sh.show_id,
	sh.show_date,
	sh.venue,
  sh.city,
  sh.state AS location,
  sh.notes,
	st.set_name,
	se.raw_entry
FROM
	shows sh
LEFT JOIN SETS st
	ON
	sh.show_id = st.show_id
LEFT JOIN set_entries se
	ON
	st.id = se.set_id
WHERE
	sh.show_id = $1
ORDER BY
	st.position,
	se.position
`

type GetShowFromIDRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	Location string
	Notes    sql.NullString
	SetName  sql.NullString
	RawEntry sql.NullString
}

func (q *Queries) GetShowFromID(ctx context.Context, showID int32) ([]GetShowFromIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowFromID, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowFromIDRow
	for rows.Next() {
		var i GetShowFromIDRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Notes,
			&i.SetName,
			&i.RawEntry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsBetweenDates = `-- name: GetShowsBetweenDates :many
SELECT
  sh.show_id,
	sh.show_date,
	sh.venue,
	sh.city,
	sh.state AS location,
  sh.notes,
  COUNT(*) OVER ()
FROM
	shows sh
WHERE
sh.show_date BETWEEN $1 AND $2
GROUP BY
	sh.show_date, sh.venue, sh.show_id 
ORDER BY
	sh.show_date, sh.show_id
LIMIT $4 OFFSET $3
`

type GetShowsBetweenDatesParams struct {
	StartDate  time.Time
	EndDate    time.Time
	PageOffset int32
	PageLimit  int32
}

type GetShowsBetweenDatesRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	Location string
	Notes    sql.NullString
	Count    int64
}

func (q *Queries) GetShowsBetweenDates(ctx context.Context, arg GetShowsBetweenDatesParams) ([]GetShowsBetweenDatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsBetweenDates,
		arg.StartDate,
		arg.EndDate,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsBetweenDatesRow
	for rows.Next() {
		var i GetShowsBetweenDatesRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Notes,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsFromCity = `-- name: GetShowsFromCity :many
SELECT
  sh.show_id,
  sh.show_date,
  sh.venue,
  sh.city,
  sh.state AS location,
  sh.notes,
  COUNT(*) OVER ()
FROM shows sh
WHERE sh.city ILIKE $1
ORDER BY sh.show_date, sh.show_id
LIMIT $3 OFFSET $2
`

type GetShowsFromCityParams struct {
	City       string
	PageOffset int32
	PageLimit  int32
}

type GetShowsFromCityRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	Location string
	Notes    sql.NullString
	Count    int64
}

func (q *Queries) GetShowsFromCity(ctx context.Context, arg GetShowsFromCityParams) ([]GetShowsFromCityRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsFromCity, arg.City, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsFromCityRow
	for rows.Next() {
		var i GetShowsFromCityRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Notes,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsFromLocation = `-- name: GetShowsFromLocation :many
SELECT
  sh.show_id,
  sh.show_date,
  sh.venue,
  sh.city,
  sh.state AS location,
  sh.notes,
  COUNT(*) OVER ()
FROM shows sh
WHERE LOWER(sh.state) = LOWER($1)
ORDER BY sh.show_date, sh.show_id
LIMIT $3 OFFSET $2
`

type GetShowsFromLocationParams struct {
	Location   string
	PageOffset int32
	PageLimit  int32
}

type GetShowsFromLocationRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	Location string
	Notes    sql.NullString
	Count    int64
}

func (q *Queries) GetShowsFromLocation(ctx context.Context, arg GetShowsFromLocationParams) ([]GetShowsFromLocationRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsFromLocation, arg.Location, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsFromLocationRow
	for rows.Next() {
		var i GetShowsFromLocationRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Notes,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsFromSetName = `-- name: GetShowsFromSetName :many
SELECT
	sh.show_id,
	sh.show_date,
	sh.venue,
	sh.city,
	sh.state AS location,
  sh.notes,
  COUNT(*) OVER ()
FROM shows sh
JOIN "sets" s ON s.show_id = sh.show_id 
WHERE s.set_name = $1
ORDER BY sh.show_date, sh.show_id
LIMIT $3 OFFSET $2
`

type GetShowsFromSetNameParams struct {
	SetName    string
	PageOffset int32
	PageLimit  int32
}

type GetShowsFromSetNameRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	Location string
	Notes    sql.NullString
	Count    int64
}

func (q *Queries) GetShowsFromSetName(ctx context.Context, arg GetShowsFromSetNameParams) ([]GetShowsFromSetNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsFromSetName, arg.SetName, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsFromSetNameRow
	for rows.Next() {
		var i GetShowsFromSetNameRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Notes,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsFromSongName = `-- name: GetShowsFromSongName :many
SELECT
  sh.show_id,
  sh.show_date,
  sh.venue,
  sh.city,
  sh.state AS location,
  sh.notes,
  COUNT(*) OVER ()
FROM shows sh
JOIN "sets" st ON st.show_id = sh.show_id
JOIN set_entries se ON se.set_id = st.id
WHERE se.raw_entry ILIKE $1
ORDER BY sh.show_date, sh.show_id
LIMIT $3 OFFSET $2
`

type GetShowsFromSongNameParams struct {
	SongName   string
	PageOffset int32
	PageLimit  int32
}

type GetShowsFromSongNameRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	Location string
	Notes    sql.NullString
	Count    int64
}

func (q *Queries) GetShowsFromSongName(ctx context.Context, arg GetShowsFromSongNameParams) ([]GetShowsFromSongNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsFromSongName, arg.SongName, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsFromSongNameRow
	for rows.Next() {
		var i GetShowsFromSongNameRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Notes,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsFromYear = `-- name: GetShowsFromYear :many
SELECT
  sh.show_id,
  sh.show_date,
  sh.venue,
  sh.city,
  sh.state AS location,
  sh.notes,
  COUNT(*) OVER ()
FROM shows sh
WHERE EXTRACT(YEAR FROM sh.show_date) = $1::int
ORDER BY sh.show_date, show_id
LIMIT $3 OFFSET $2
`

type GetShowsFromYearParams struct {
	Year       int32
	PageOffset int32
	PageLimit  int32
}

type GetShowsFromYearRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	Location string
	Notes    sql.NullString
	Count    int64
}

func (q *Queries) GetShowsFromYear(ctx context.Context, arg GetShowsFromYearParams) ([]GetShowsFromYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsFromYear, arg.Year, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsFromYearRow
	for rows.Next() {
		var i GetShowsFromYearRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Notes,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsFromYearAndLocation = `-- name: GetShowsFromYearAndLocation :many
SELECT
  sh.show_id,
  sh.show_date,
  sh.venue,
  sh.city,
  sh.state AS location,
  sh.notes,
  COUNT(*) OVER ()
FROM shows sh
WHERE EXTRACT(YEAR FROM sh.show_date) = $1::int
AND LOWER(sh.state) = LOWER($2)
ORDER BY sh.show_date, sh.show_id
LIMIT $4 OFFSET $3
`

type GetShowsFromYearAndLocationParams struct {
	Year       int32
	Location   string
	PageOffset int32
	PageLimit  int32
}

type GetShowsFromYearAndLocationRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	Location string
	Notes    sql.NullString
	Count    int64
}

func (q *Queries) GetShowsFromYearAndLocation(ctx context.Context, arg GetShowsFromYearAndLocationParams) ([]GetShowsFromYearAndLocationRow, error) {
	rows, err := q.db.QueryContext(ctx, getShowsFromYearAndLocation,
		arg.Year,
		arg.Location,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsFromYearAndLocationRow
	for rows.Next() {
		var i GetShowsFromYearAndLocationRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Notes,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidLocations = `-- name: GetValidLocations :many
SELECT DISTINCT LOWER(state) AS location FROM shows
`

func (q *Queries) GetValidLocations(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getValidLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var location string
		if err := rows.Scan(&location); err != nil {
			return nil, err
		}
		items = append(items, location)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVenue = `-- name: SearchByVenue :many
SELECT
  sh.show_id,
	sh.show_date,
	sh.venue,
  sh.city,
  sh.state AS location,
  sh.notes,
  COUNT(*) OVER ()
FROM
	shows sh
WHERE venue ILIKE $1
ORDER BY
  sh.show_id,
	sh.venue,
	sh.show_date
LIMIT $3 OFFSET $2
`

type SearchByVenueParams struct {
	VenueName  string
	PageOffset int32
	PageLimit  int32
}

type SearchByVenueRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	Location string
	Notes    sql.NullString
	Count    int64
}

func (q *Queries) SearchByVenue(ctx context.Context, arg SearchByVenueParams) ([]SearchByVenueRow, error) {
	rows, err := q.db.QueryContext(ctx, searchByVenue, arg.VenueName, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchByVenueRow
	for rows.Next() {
		var i SearchByVenueRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Notes,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showsWithShowNotes = `-- name: ShowsWithShowNotes :many
SELECT 
	sh.show_id,
	sh.show_date,
	sh.venue,
	sh.city,
	sh.state AS location,
	sh.notes,
  COUNT(*) OVER ()
FROM shows sh
WHERE sh.notes IS NOT NULL AND sh.notes != ''
ORDER BY sh.show_date, sh.show_id
LIMIT $2 OFFSET $1
`

type ShowsWithShowNotesParams struct {
	PageOffset int32
	PageLimit  int32
}

type ShowsWithShowNotesRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	Location string
	Notes    sql.NullString
	Count    int64
}

func (q *Queries) ShowsWithShowNotes(ctx context.Context, arg ShowsWithShowNotesParams) ([]ShowsWithShowNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, showsWithShowNotes, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowsWithShowNotesRow
	for rows.Next() {
		var i ShowsWithShowNotesRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Notes,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showsWithoutNotes = `-- name: ShowsWithoutNotes :many
SELECT
  sh.show_id,
  sh.show_date,
  sh.venue,
  sh.city,
  sh.state AS location,
  COUNT(*) OVER ()
FROM shows sh
WHERE sh.notes IS NULL OR sh.notes = ''
ORDER BY sh.show_date, sh.show_id
LIMIT $2 OFFSET $1
`

type ShowsWithoutNotesParams struct {
	PageOffset int32
	PageLimit  int32
}

type ShowsWithoutNotesRow struct {
	ShowID   int32
	ShowDate time.Time
	Venue    string
	City     string
	Location string
	Count    int64
}

func (q *Queries) ShowsWithoutNotes(ctx context.Context, arg ShowsWithoutNotesParams) ([]ShowsWithoutNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, showsWithoutNotes, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowsWithoutNotesRow
	for rows.Next() {
		var i ShowsWithoutNotesRow
		if err := rows.Scan(
			&i.ShowID,
			&i.ShowDate,
			&i.Venue,
			&i.City,
			&i.Location,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const songStats = `-- name: SongStats :one
SELECT
  count(*) AS times_played,
  min(sh.show_date)::date AS first_played,
  max(sh.show_date)::date AS last_played
FROM shows sh 
JOIN "sets" st ON st.show_id = sh.show_id
JOIN set_entries se ON se.set_id = s.id
WHERE se.song_name ILIKE $1
`

type SongStatsRow struct {
	TimesPlayed int64
	FirstPlayed time.Time
	LastPlayed  time.Time
}

func (q *Queries) SongStats(ctx context.Context, songName sql.NullString) (SongStatsRow, error) {
	row := q.db.QueryRowContext(ctx, songStats, songName)
	var i SongStatsRow
	err := row.Scan(&i.TimesPlayed, &i.FirstPlayed, &i.LastPlayed)
	return i, err
}
