x-app: &app
  build:
    context: .
  image: deadabase:local
  environment:
    DB_URL: ${DB_URL}

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    <<: *app
    depends_on:
      db:
        condition: service_healthy
    command: ["./goose", "-dir", "sql/schema", "postgres", "${DB_URL}" , "up"]

  import:
    <<: *app
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: ["./importer"]

  api:
    <<: *app
    tty: true
    depends_on:
      import:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
